spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers:
      - 'localhost:9092'

management:
  endpoint:
    health:
      show-details: always