spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/api?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers:
      - 'localhost:9092'

management:
  endpoint:
    health:
      show-details: always